[package]
name = "a3s-oci-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Command-line frontend for A3S OCI Runtime"

[[bin]]
name = "a3s-oci"
path = "src/main.rs"

[dependencies]
a3s-oci-sdk = { path = "../sdk" }
a3s-oci-runtime = { path = "../runtime" }
clap.workspace = true
fs2.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[dev-dependencies]
a3s-oci-core = { path = "../core" }
async-trait.workspace = true
tempfile = "3.20"

[lints]
workspace = true
